version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parth123
      MYSQL_USER: parth
      MYSQL_PASSWORD: 19122000
    ports:
      - "3306:3306"

  authservice:
    image: partharanke/authentication
    restart: always
    ports:
      - "8080:8080"
  
  customerservice:
    image: partharanke/customerservice
    restart: always
    ports:
      - "5000:5000"
  
  tasksservice:
    image: partharanke/tasksservice
    restart: always
    ports:
      - ":5050:5050"
