version: '3'

services:
  database:
    image: partharanke/db
    restart: always
    ports:
      - "3306:3306"

  authservice:
    image: partharanke/authentication
    restart: always
    ports:
      - "8080:8080"
  
  customerservice:
    image: partharanke/customerservice
    restart: always
    ports:
      - "5000:5000"
  
  tasksservice:
    image: partharanke/taskservice
    restart: always
    ports:
      - ":5050:5050"
